// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvwfndKdMHXnfCKfwrtVLPWiN8TQWj9qo',
    appId: '1:621205124669:web:e462bb94a0347fa1e21c54',
    messagingSenderId: '621205124669',
    projectId: 'musicwave-43a80',
    authDomain: 'musicwave-43a80.firebaseapp.com',
    storageBucket: 'musicwave-43a80.appspot.com',
    measurementId: 'G-B3J6G1DF1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUrC9d5028JecezK1RCTkrJr8N6i10oa8',
    appId: '1:621205124669:android:ab8408fe51af67d5e21c54',
    messagingSenderId: '621205124669',
    projectId: 'musicwave-43a80',
    storageBucket: 'musicwave-43a80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuAyhONjRbBI47JWxlmdRMcdhWSaCEls',
    appId: '1:621205124669:ios:4fd32df5fcbfd10ce21c54',
    messagingSenderId: '621205124669',
    projectId: 'musicwave-43a80',
    storageBucket: 'musicwave-43a80.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuAyhONjRbBI47JWxlmdRMcdhWSaCEls',
    appId: '1:621205124669:ios:4fd32df5fcbfd10ce21c54',
    messagingSenderId: '621205124669',
    projectId: 'musicwave-43a80',
    storageBucket: 'musicwave-43a80.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvwfndKdMHXnfCKfwrtVLPWiN8TQWj9qo',
    appId: '1:621205124669:web:64f7cdf1bf750bbae21c54',
    messagingSenderId: '621205124669',
    projectId: 'musicwave-43a80',
    authDomain: 'musicwave-43a80.firebaseapp.com',
    storageBucket: 'musicwave-43a80.appspot.com',
    measurementId: 'G-E5M60SJ88N',
  );

}